### ISSUE TITLE
No transparent images on PNG saving of metamodels

### ISSUE THREAD

**Issue by jcmunozf** [SPLA/VARIAMOS#257]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Improvement request
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

When you save a png file, the application ask if you want a transparent background. No matter your selection, the file is created with a background.

## Expected behavior

If you select transparent background, the file should be created without a background.

## Minimal reproduction of the problem with instructions

Switch to the syntax metamodel, press the save button, change the extension to png and accept the transparent background. It should also occur in others perspectives.

## What is the motivation / use case for changing the behavior?

It is an existing features useful to obtain the models for other destinations

## Environment
Variamos version: 

Most recent development branch. Works of in the master branch.

For Tooling issues:  
Platform:    
Others:

**Comment by lufe089** [comment]
Closed in pull request #261
